# Это Поддерживаемые платформы модели финансирования

github: rstoenescu
patreon: # quasarframework
open_collective: # Заменить одним открытым коллективным именем пользователя
ko_fi: # Заменить одним именем пользователя Ko-fi
tidelift: # Замените одним именем платформы Tidelift/именем пакета, например, npm/babel
custom: # Заменить одним настраиваемым URL-адресом спонсорской поддержки
